import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Header from "./_components/Header";
import { AuthProvider } from "./_components/auth-provider";
import SideNavigationBar from "@/components/SideNavigationBar";
import { auth } from "@/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const session = await auth();
  const user_id =session?.user.id
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-black">
        <TRPCReactProvider>
         
          <AuthProvider>
          <Header/>
          {user_id && <SideNavigationBar user_id={user_id} />}
          <main className=" pl-20 pt-20 min-h-screen">
          {children}
        </main>
        </AuthProvider></TRPCReactProvider>
      </body>
    </html>
  );
}
